app_group:
  - read:
      path: /apps/topologies.eda.nokia.com
      method: GET

patch:
  - update:
      path: /apps/topologies.eda.nokia.com/v1alpha1/deviationoverlays/{name}
      method: PATCH
  - update:
      path: /apps/topologies.eda.nokia.com/v1alpha1/lldpoverlays/{name}
      method: PATCH
  - update:
      path: /apps/topologies.eda.nokia.com/v1alpha1/topologies/{name}
      method: PATCH
  - update:
      path: /apps/topologies.eda.nokia.com/v1alpha1/topologygroupings/{name}
      method: PATCH
  - update:
      path: /apps/topologies.eda.nokia.com/v1alpha1/trafficrateoverlays/{name}
      method: PATCH

resource_history:
  - read:
      path: /apps/topologies.eda.nokia.com/v1alpha1/deviationoverlays/{name}/_revs
      method: GET
  - read:
      path: /apps/topologies.eda.nokia.com/v1alpha1/lldpoverlays/{name}/_revs
      method: GET
  - read:
      path: /apps/topologies.eda.nokia.com/v1alpha1/topologies/{name}/_revs
      method: GET
  - read:
      path: /apps/topologies.eda.nokia.com/v1alpha1/topologygroupings/{name}/_revs
      method: GET
  - read:
      path: /apps/topologies.eda.nokia.com/v1alpha1/trafficrateoverlays/{name}/_revs
      method: GET

resource_list:
  - read:
      path: /apps/topologies.eda.nokia.com/v1alpha1
      method: GET

resource_topology:
  - read:
      path: /apps/topologies.eda.nokia.com/v1alpha1/deviationoverlays/{name}/_topology
      method: GET
  - read:
      path: /apps/topologies.eda.nokia.com/v1alpha1/lldpoverlays/{name}/_topology
      method: GET
  - read:
      path: /apps/topologies.eda.nokia.com/v1alpha1/topologies/{name}/_topology
      method: GET
  - read:
      path: /apps/topologies.eda.nokia.com/v1alpha1/topologygroupings/{name}/_topology
      method: GET
  - read:
      path: /apps/topologies.eda.nokia.com/v1alpha1/trafficrateoverlays/{name}/_topology
      method: GET

status:
  - delete:
      path: /apps/topologies.eda.nokia.com/v1alpha1/deviationoverlays/{name}
      method: DELETE
  - delete:
      path: /apps/topologies.eda.nokia.com/v1alpha1/lldpoverlays/{name}
      method: DELETE
  - delete:
      path: /apps/topologies.eda.nokia.com/v1alpha1/topologies/{name}
      method: DELETE
  - delete:
      path: /apps/topologies.eda.nokia.com/v1alpha1/topologygroupings/{name}
      method: DELETE
  - delete:
      path: /apps/topologies.eda.nokia.com/v1alpha1/trafficrateoverlays/{name}
      method: DELETE

ui_result:
  - read:
      path: /apps/topologies.eda.nokia.com/v1alpha1/_ui/{pathname}
      method: GET

com.nokia.eda.topologies.v1alpha1.deviation_overlay:
  - create:
      path: /apps/topologies.eda.nokia.com/v1alpha1/deviationoverlays
      method: POST
  - read:
      path: /apps/topologies.eda.nokia.com/v1alpha1/deviationoverlays/{name}
      method: GET
  - update:
      path: /apps/topologies.eda.nokia.com/v1alpha1/deviationoverlays/{name}
      method: PUT

com.nokia.eda.topologies.v1alpha1.deviation_overlay_list:
  - read:
      path: /apps/topologies.eda.nokia.com/v1alpha1/deviationoverlays
      method: GET
  - delete:
      path: /apps/topologies.eda.nokia.com/v1alpha1/deviationoverlays
      method: DELETE

com.nokia.eda.topologies.v1alpha1.deviation_overlay_deleted_resources:
  - read:
      path: /apps/topologies.eda.nokia.com/v1alpha1/deviationoverlays/_deleted
      method: GET

com.nokia.eda.topologies.v1alpha1.lldp_overlay:
  - create:
      path: /apps/topologies.eda.nokia.com/v1alpha1/lldpoverlays
      method: POST
  - read:
      path: /apps/topologies.eda.nokia.com/v1alpha1/lldpoverlays/{name}
      method: GET
  - update:
      path: /apps/topologies.eda.nokia.com/v1alpha1/lldpoverlays/{name}
      method: PUT

com.nokia.eda.topologies.v1alpha1.lldp_overlay_list:
  - read:
      path: /apps/topologies.eda.nokia.com/v1alpha1/lldpoverlays
      method: GET
  - delete:
      path: /apps/topologies.eda.nokia.com/v1alpha1/lldpoverlays
      method: DELETE

com.nokia.eda.topologies.v1alpha1.lldp_overlay_deleted_resources:
  - read:
      path: /apps/topologies.eda.nokia.com/v1alpha1/lldpoverlays/_deleted
      method: GET

com.nokia.eda.topologies.v1alpha1.topology:
  - create:
      path: /apps/topologies.eda.nokia.com/v1alpha1/topologies
      method: POST
  - read:
      path: /apps/topologies.eda.nokia.com/v1alpha1/topologies/{name}
      method: GET
  - update:
      path: /apps/topologies.eda.nokia.com/v1alpha1/topologies/{name}
      method: PUT

com.nokia.eda.topologies.v1alpha1.topology_grouping:
  - create:
      path: /apps/topologies.eda.nokia.com/v1alpha1/topologygroupings
      method: POST
  - read:
      path: /apps/topologies.eda.nokia.com/v1alpha1/topologygroupings/{name}
      method: GET
  - update:
      path: /apps/topologies.eda.nokia.com/v1alpha1/topologygroupings/{name}
      method: PUT

com.nokia.eda.topologies.v1alpha1.topology_grouping_list:
  - read:
      path: /apps/topologies.eda.nokia.com/v1alpha1/topologygroupings
      method: GET
  - delete:
      path: /apps/topologies.eda.nokia.com/v1alpha1/topologygroupings
      method: DELETE

com.nokia.eda.topologies.v1alpha1.topology_grouping_deleted_resources:
  - read:
      path: /apps/topologies.eda.nokia.com/v1alpha1/topologygroupings/_deleted
      method: GET

com.nokia.eda.topologies.v1alpha1.topology_list:
  - read:
      path: /apps/topologies.eda.nokia.com/v1alpha1/topologies
      method: GET
  - delete:
      path: /apps/topologies.eda.nokia.com/v1alpha1/topologies
      method: DELETE

com.nokia.eda.topologies.v1alpha1.topology_deleted_resources:
  - read:
      path: /apps/topologies.eda.nokia.com/v1alpha1/topologies/_deleted
      method: GET

com.nokia.eda.topologies.v1alpha1.traffic_rate_overlay:
  - create:
      path: /apps/topologies.eda.nokia.com/v1alpha1/trafficrateoverlays
      method: POST
  - read:
      path: /apps/topologies.eda.nokia.com/v1alpha1/trafficrateoverlays/{name}
      method: GET
  - update:
      path: /apps/topologies.eda.nokia.com/v1alpha1/trafficrateoverlays/{name}
      method: PUT

com.nokia.eda.topologies.v1alpha1.traffic_rate_overlay_list:
  - read:
      path: /apps/topologies.eda.nokia.com/v1alpha1/trafficrateoverlays
      method: GET
  - delete:
      path: /apps/topologies.eda.nokia.com/v1alpha1/trafficrateoverlays
      method: DELETE

com.nokia.eda.topologies.v1alpha1.traffic_rate_overlay_deleted_resources:
  - read:
      path: /apps/topologies.eda.nokia.com/v1alpha1/trafficrateoverlays/_deleted
      method: GET

totalPaths: 28
totalSchemas: 53
usedSchemas: 22
unusedSchemas: 31
unusedSchemaList:
  - AppGroupVersion
  - ErrorIndex
  - ErrorItem
  - ErrorResponse
  - K8SPatchOp
  - OverlayState
  - Resource
  - ResourceHistoryEntry
  - StatusDetails
  - TopoAttrMetadata
  - TopoElemMetadata
  - TopoLinkEndpoint
  - TopoNodeGrouping
  - TopoOverlayEndpoint
  - TopoOverlayEndpointState
  - TopoOverlayLink
  - TopoOverlayLinkState
  - TopoOverlayNode
  - TopoOverlayNodeState
  - TopoSchema
  - Topology
  - com.nokia.eda.topologies.v1alpha1.DeviationOverlay_DeletedResourceEntry
  - com.nokia.eda.topologies.v1alpha1.DeviationOverlay_metadata
  - com.nokia.eda.topologies.v1alpha1.LldpOverlay_DeletedResourceEntry
  - com.nokia.eda.topologies.v1alpha1.LldpOverlay_metadata
  - com.nokia.eda.topologies.v1alpha1.TopologyGrouping_DeletedResourceEntry
  - com.nokia.eda.topologies.v1alpha1.TopologyGrouping_metadata
  - com.nokia.eda.topologies.v1alpha1.Topology_DeletedResourceEntry
  - com.nokia.eda.topologies.v1alpha1.Topology_metadata
  - com.nokia.eda.topologies.v1alpha1.TrafficRateOverlay_DeletedResourceEntry
  - com.nokia.eda.topologies.v1alpha1.TrafficRateOverlay_metadata
